// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pojo.proto

package com.example.protobufdemo.proto;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobufdemo.proto.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string first_name = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string first_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional string last_name = 3;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>optional string last_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>optional string email = 4;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
   */
  java.util.List<com.example.protobufdemo.proto.Student.PhoneNumber> 
      getPhoneList();
  /**
   * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
   */
  com.example.protobufdemo.proto.Student.PhoneNumber getPhone(int index);
  /**
   * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
   */
  int getPhoneCount();
  /**
   * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
   */
  java.util.List<? extends com.example.protobufdemo.proto.Student.PhoneNumberOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
   */
  com.example.protobufdemo.proto.Student.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index);
}
