// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pojo.proto

package com.example.protobufdemo.proto;

/**
 * Protobuf type {@code protobufdemo.proto.Course}
 */
public final class Course extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protobufdemo.proto.Course)
        CourseOrBuilder {
    // Use Course.newBuilder() to construct.
    private Course(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Course() {
        id_ = 0;
        courseName_ = "";
        student_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private Course(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        id_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        courseName_ = s;
                        break;
                    }
                    case 26: {
                        if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                            student_ = new java.util.ArrayList<com.example.protobufdemo.proto.Student>();
                            mutable_bitField0_ |= 0x00000004;
                        }
                        student_.add(
                                input.readMessage(com.example.protobufdemo.proto.Student.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                student_ = java.util.Collections.unmodifiableList(student_);
            }
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.example.protobufdemo.proto.PojoProto.internal_static_protobufdemo_proto_Course_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.example.protobufdemo.proto.PojoProto.internal_static_protobufdemo_proto_Course_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Course.class, Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;

    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
        return id_;
    }

    public static final int COURSE_NAME_FIELD_NUMBER = 2;
    private volatile Object courseName_;

    /**
     * <code>optional string course_name = 2;</code>
     */
    public String getCourseName() {
        Object ref = courseName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            courseName_ = s;
            return s;
        }
    }

    /**
     * <code>optional string course_name = 2;</code>
     */
    public com.google.protobuf.ByteString
    getCourseNameBytes() {
        Object ref = courseName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            courseName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int STUDENT_FIELD_NUMBER = 3;
    private java.util.List<com.example.protobufdemo.proto.Student> student_;

    /**
     * <code>repeated .protobufdemo.proto.Student student = 3;</code>
     */
    public java.util.List<com.example.protobufdemo.proto.Student> getStudentList() {
        return student_;
    }

    /**
     * <code>repeated .protobufdemo.proto.Student student = 3;</code>
     */
    public java.util.List<? extends com.example.protobufdemo.proto.StudentOrBuilder>
    getStudentOrBuilderList() {
        return student_;
    }

    /**
     * <code>repeated .protobufdemo.proto.Student student = 3;</code>
     */
    public int getStudentCount() {
        return student_.size();
    }

    /**
     * <code>repeated .protobufdemo.proto.Student student = 3;</code>
     */
    public com.example.protobufdemo.proto.Student getStudent(int index) {
        return student_.get(index);
    }

    /**
     * <code>repeated .protobufdemo.proto.Student student = 3;</code>
     */
    public com.example.protobufdemo.proto.StudentOrBuilder getStudentOrBuilder(
            int index) {
        return student_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (id_ != 0) {
            output.writeInt32(1, id_);
        }
        if (!getCourseNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, courseName_);
        }
        for (int i = 0; i < student_.size(); i++) {
            output.writeMessage(3, student_.get(i));
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, id_);
        }
        if (!getCourseNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, courseName_);
        }
        for (int i = 0; i < student_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, student_.get(i));
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Course)) {
            return super.equals(obj);
        }
        Course other = (Course) obj;

        boolean result = true;
        result = result && (getId()
                == other.getId());
        result = result && getCourseName()
                .equals(other.getCourseName());
        result = result && getStudentList()
                .equals(other.getStudentList());
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + COURSE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getCourseName().hashCode();
        if (getStudentCount() > 0) {
            hash = (37 * hash) + STUDENT_FIELD_NUMBER;
            hash = (53 * hash) + getStudentList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Course parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Course parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Course parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Course parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Course parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Course parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Course parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Course parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Course parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Course parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Course prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code protobufdemo.proto.Course}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:protobufdemo.proto.Course)
            com.example.protobufdemo.proto.CourseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.example.protobufdemo.proto.PojoProto.internal_static_protobufdemo_proto_Course_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.example.protobufdemo.proto.PojoProto.internal_static_protobufdemo_proto_Course_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Course.class, Builder.class);
        }

        // Construct using com.example.protobufdemo.proto.Course.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getStudentFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            id_ = 0;

            courseName_ = "";

            if (studentBuilder_ == null) {
                student_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000004);
            } else {
                studentBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.example.protobufdemo.proto.PojoProto.internal_static_protobufdemo_proto_Course_descriptor;
        }

        public Course getDefaultInstanceForType() {
            return Course.getDefaultInstance();
        }

        public Course build() {
            Course result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public Course buildPartial() {
            Course result = new Course(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.id_ = id_;
            result.courseName_ = courseName_;
            if (studentBuilder_ == null) {
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    student_ = java.util.Collections.unmodifiableList(student_);
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.student_ = student_;
            } else {
                result.student_ = studentBuilder_.build();
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Course) {
                return mergeFrom((Course) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Course other) {
            if (other == Course.getDefaultInstance()) return this;
            if (other.getId() != 0) {
                setId(other.getId());
            }
            if (!other.getCourseName().isEmpty()) {
                courseName_ = other.courseName_;
                onChanged();
            }
            if (studentBuilder_ == null) {
                if (!other.student_.isEmpty()) {
                    if (student_.isEmpty()) {
                        student_ = other.student_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureStudentIsMutable();
                        student_.addAll(other.student_);
                    }
                    onChanged();
                }
            } else {
                if (!other.student_.isEmpty()) {
                    if (studentBuilder_.isEmpty()) {
                        studentBuilder_.dispose();
                        studentBuilder_ = null;
                        student_ = other.student_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                        studentBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getStudentFieldBuilder() : null;
                    } else {
                        studentBuilder_.addAllMessages(other.student_);
                    }
                }
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Course parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Course) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private int id_;

        /**
         * <code>optional int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        /**
         * <code>optional int32 id = 1;</code>
         */
        public Builder setId(int value) {

            id_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional int32 id = 1;</code>
         */
        public Builder clearId() {

            id_ = 0;
            onChanged();
            return this;
        }

        private Object courseName_ = "";

        /**
         * <code>optional string course_name = 2;</code>
         */
        public String getCourseName() {
            Object ref = courseName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                courseName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>optional string course_name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getCourseNameBytes() {
            Object ref = courseName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                courseName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string course_name = 2;</code>
         */
        public Builder setCourseName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            courseName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional string course_name = 2;</code>
         */
        public Builder clearCourseName() {

            courseName_ = getDefaultInstance().getCourseName();
            onChanged();
            return this;
        }

        /**
         * <code>optional string course_name = 2;</code>
         */
        public Builder setCourseNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            courseName_ = value;
            onChanged();
            return this;
        }

        private java.util.List<com.example.protobufdemo.proto.Student> student_ =
                java.util.Collections.emptyList();

        private void ensureStudentIsMutable() {
            if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                student_ = new java.util.ArrayList<com.example.protobufdemo.proto.Student>(student_);
                bitField0_ |= 0x00000004;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.example.protobufdemo.proto.Student, com.example.protobufdemo.proto.Student.Builder, com.example.protobufdemo.proto.StudentOrBuilder> studentBuilder_;

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public java.util.List<com.example.protobufdemo.proto.Student> getStudentList() {
            if (studentBuilder_ == null) {
                return java.util.Collections.unmodifiableList(student_);
            } else {
                return studentBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public int getStudentCount() {
            if (studentBuilder_ == null) {
                return student_.size();
            } else {
                return studentBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public com.example.protobufdemo.proto.Student getStudent(int index) {
            if (studentBuilder_ == null) {
                return student_.get(index);
            } else {
                return studentBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public Builder setStudent(
                int index, com.example.protobufdemo.proto.Student value) {
            if (studentBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureStudentIsMutable();
                student_.set(index, value);
                onChanged();
            } else {
                studentBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public Builder setStudent(
                int index, com.example.protobufdemo.proto.Student.Builder builderForValue) {
            if (studentBuilder_ == null) {
                ensureStudentIsMutable();
                student_.set(index, builderForValue.build());
                onChanged();
            } else {
                studentBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public Builder addStudent(com.example.protobufdemo.proto.Student value) {
            if (studentBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureStudentIsMutable();
                student_.add(value);
                onChanged();
            } else {
                studentBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public Builder addStudent(
                int index, com.example.protobufdemo.proto.Student value) {
            if (studentBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureStudentIsMutable();
                student_.add(index, value);
                onChanged();
            } else {
                studentBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public Builder addStudent(
                com.example.protobufdemo.proto.Student.Builder builderForValue) {
            if (studentBuilder_ == null) {
                ensureStudentIsMutable();
                student_.add(builderForValue.build());
                onChanged();
            } else {
                studentBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public Builder addStudent(
                int index, com.example.protobufdemo.proto.Student.Builder builderForValue) {
            if (studentBuilder_ == null) {
                ensureStudentIsMutable();
                student_.add(index, builderForValue.build());
                onChanged();
            } else {
                studentBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public Builder addAllStudent(
                Iterable<? extends com.example.protobufdemo.proto.Student> values) {
            if (studentBuilder_ == null) {
                ensureStudentIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, student_);
                onChanged();
            } else {
                studentBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public Builder clearStudent() {
            if (studentBuilder_ == null) {
                student_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
            } else {
                studentBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public Builder removeStudent(int index) {
            if (studentBuilder_ == null) {
                ensureStudentIsMutable();
                student_.remove(index);
                onChanged();
            } else {
                studentBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public com.example.protobufdemo.proto.Student.Builder getStudentBuilder(
                int index) {
            return getStudentFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public com.example.protobufdemo.proto.StudentOrBuilder getStudentOrBuilder(
                int index) {
            if (studentBuilder_ == null) {
                return student_.get(index);
            } else {
                return studentBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public java.util.List<? extends com.example.protobufdemo.proto.StudentOrBuilder>
        getStudentOrBuilderList() {
            if (studentBuilder_ != null) {
                return studentBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(student_);
            }
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public com.example.protobufdemo.proto.Student.Builder addStudentBuilder() {
            return getStudentFieldBuilder().addBuilder(
                    com.example.protobufdemo.proto.Student.getDefaultInstance());
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public com.example.protobufdemo.proto.Student.Builder addStudentBuilder(
                int index) {
            return getStudentFieldBuilder().addBuilder(
                    index, com.example.protobufdemo.proto.Student.getDefaultInstance());
        }

        /**
         * <code>repeated .protobufdemo.proto.Student student = 3;</code>
         */
        public java.util.List<com.example.protobufdemo.proto.Student.Builder>
        getStudentBuilderList() {
            return getStudentFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.example.protobufdemo.proto.Student, com.example.protobufdemo.proto.Student.Builder, com.example.protobufdemo.proto.StudentOrBuilder>
        getStudentFieldBuilder() {
            if (studentBuilder_ == null) {
                studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        com.example.protobufdemo.proto.Student, com.example.protobufdemo.proto.Student.Builder, com.example.protobufdemo.proto.StudentOrBuilder>(
                        student_,
                        ((bitField0_ & 0x00000004) == 0x00000004),
                        getParentForChildren(),
                        isClean());
                student_ = null;
            }
            return studentBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:protobufdemo.proto.Course)
    }

    // @@protoc_insertion_point(class_scope:protobufdemo.proto.Course)
    private static final Course DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new Course();
    }

    public static Course getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Course>
            PARSER = new com.google.protobuf.AbstractParser<Course>() {
        public Course parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Course(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Course> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Course> getParserForType() {
        return PARSER;
    }

    public Course getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

