// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pojo.proto

package com.example.protobufdemo.proto;

public interface CourseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobufdemo.proto.Course)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string course_name = 2;</code>
     */
    String getCourseName();

    /**
     * <code>optional string course_name = 2;</code>
     */
    com.google.protobuf.ByteString
    getCourseNameBytes();

    /**
     * <code>repeated .protobufdemo.proto.Student student = 3;</code>
     */
    java.util.List<com.example.protobufdemo.proto.Student>
    getStudentList();

    /**
     * <code>repeated .protobufdemo.proto.Student student = 3;</code>
     */
    com.example.protobufdemo.proto.Student getStudent(int index);

    /**
     * <code>repeated .protobufdemo.proto.Student student = 3;</code>
     */
    int getStudentCount();

    /**
     * <code>repeated .protobufdemo.proto.Student student = 3;</code>
     */
    java.util.List<? extends com.example.protobufdemo.proto.StudentOrBuilder>
    getStudentOrBuilderList();

    /**
     * <code>repeated .protobufdemo.proto.Student student = 3;</code>
     */
    com.example.protobufdemo.proto.StudentOrBuilder getStudentOrBuilder(
            int index);
}
