// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pojo.proto

package com.example.protobufdemo.proto;

public interface StudentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobufdemo.proto.Student)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string first_name = 2;</code>
     */
    String getFirstName();

    /**
     * <code>optional string first_name = 2;</code>
     */
    com.google.protobuf.ByteString
    getFirstNameBytes();

    /**
     * <code>optional string last_name = 3;</code>
     */
    String getLastName();

    /**
     * <code>optional string last_name = 3;</code>
     */
    com.google.protobuf.ByteString
    getLastNameBytes();

    /**
     * <code>optional string email = 4;</code>
     */
    String getEmail();

    /**
     * <code>optional string email = 4;</code>
     */
    com.google.protobuf.ByteString
    getEmailBytes();

    /**
     * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
     */
    java.util.List<Student.PhoneNumber>
    getPhoneList();

    /**
     * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
     */
    Student.PhoneNumber getPhone(int index);

    /**
     * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
     */
    int getPhoneCount();

    /**
     * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
     */
    java.util.List<? extends Student.PhoneNumberOrBuilder>
    getPhoneOrBuilderList();

    /**
     * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
     */
    Student.PhoneNumberOrBuilder getPhoneOrBuilder(
            int index);
}
