// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pojo.proto

package com.example.protobufdemo.proto;

/**
 * Protobuf type {@code protobufdemo.proto.Student}
 */
public final class Student extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protobufdemo.proto.Student)
        StudentOrBuilder {
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Student() {
        id_ = 0;
        firstName_ = "";
        lastName_ = "";
        email_ = "";
        phone_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private Student(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        id_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        firstName_ = s;
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        lastName_ = s;
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        email_ = s;
                        break;
                    }
                    case 42: {
                        if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                            phone_ = new java.util.ArrayList<PhoneNumber>();
                            mutable_bitField0_ |= 0x00000010;
                        }
                        phone_.add(
                                input.readMessage(PhoneNumber.parser(), extensionRegistry));
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                phone_ = java.util.Collections.unmodifiableList(phone_);
            }
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return PojoProto.internal_static_protobufdemo_proto_Student_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return PojoProto.internal_static_protobufdemo_proto_Student_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Student.class, Builder.class);
    }

    /**
     * Protobuf enum {@code protobufdemo.proto.Student.PhoneType}
     */
    public enum PhoneType
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>MOBILE = 0;</code>
         */
        MOBILE(0),
        /**
         * <code>LANDLINE = 1;</code>
         */
        LANDLINE(1),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>MOBILE = 0;</code>
         */
        public static final int MOBILE_VALUE = 0;
        /**
         * <code>LANDLINE = 1;</code>
         */
        public static final int LANDLINE_VALUE = 1;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static PhoneType valueOf(int value) {
            return forNumber(value);
        }

        public static PhoneType forNumber(int value) {
            switch (value) {
                case 0:
                    return MOBILE;
                case 1:
                    return LANDLINE;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                PhoneType> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
                    public PhoneType findValueByNumber(int number) {
                        return PhoneType.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return Student.getDescriptor().getEnumTypes().get(0);
        }

        private static final PhoneType[] VALUES = values();

        public static PhoneType valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private PhoneType(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:protobufdemo.proto.Student.PhoneType)
    }

    public interface PhoneNumberOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protobufdemo.proto.Student.PhoneNumber)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string number = 1;</code>
         */
        String getNumber();

        /**
         * <code>optional string number = 1;</code>
         */
        com.google.protobuf.ByteString
        getNumberBytes();

        /**
         * <code>optional .protobufdemo.proto.Student.PhoneType type = 2;</code>
         */
        int getTypeValue();

        /**
         * <code>optional .protobufdemo.proto.Student.PhoneType type = 2;</code>
         */
        PhoneType getType();
    }

    /**
     * Protobuf type {@code protobufdemo.proto.Student.PhoneNumber}
     */
    public static final class PhoneNumber extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:protobufdemo.proto.Student.PhoneNumber)
            PhoneNumberOrBuilder {
        // Use PhoneNumber.newBuilder() to construct.
        private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PhoneNumber() {
            number_ = "";
            type_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private PhoneNumber(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            number_ = s;
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();

                            type_ = rawValue;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return PojoProto.internal_static_protobufdemo_proto_Student_PhoneNumber_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return PojoProto.internal_static_protobufdemo_proto_Student_PhoneNumber_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            PhoneNumber.class, Builder.class);
        }

        public static final int NUMBER_FIELD_NUMBER = 1;
        private volatile Object number_;

        /**
         * <code>optional string number = 1;</code>
         */
        public String getNumber() {
            Object ref = number_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                number_ = s;
                return s;
            }
        }

        /**
         * <code>optional string number = 1;</code>
         */
        public com.google.protobuf.ByteString
        getNumberBytes() {
            Object ref = number_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                number_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TYPE_FIELD_NUMBER = 2;
        private int type_;

        /**
         * <code>optional .protobufdemo.proto.Student.PhoneType type = 2;</code>
         */
        public int getTypeValue() {
            return type_;
        }

        /**
         * <code>optional .protobufdemo.proto.Student.PhoneType type = 2;</code>
         */
        public PhoneType getType() {
            PhoneType result = PhoneType.valueOf(type_);
            return result == null ? PhoneType.UNRECOGNIZED : result;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getNumberBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
            }
            if (type_ != PhoneType.MOBILE.getNumber()) {
                output.writeEnum(2, type_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getNumberBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
            }
            if (type_ != PhoneType.MOBILE.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, type_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof PhoneNumber)) {
                return super.equals(obj);
            }
            PhoneNumber other = (PhoneNumber) obj;

            boolean result = true;
            result = result && getNumber()
                    .equals(other.getNumber());
            result = result && type_ == other.type_;
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + NUMBER_FIELD_NUMBER;
            hash = (53 * hash) + getNumber().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + type_;
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static PhoneNumber parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PhoneNumber parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PhoneNumber parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PhoneNumber parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PhoneNumber parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static PhoneNumber parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static PhoneNumber parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static PhoneNumber parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static PhoneNumber parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static PhoneNumber parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(PhoneNumber prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code protobufdemo.proto.Student.PhoneNumber}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protobufdemo.proto.Student.PhoneNumber)
                PhoneNumberOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return PojoProto.internal_static_protobufdemo_proto_Student_PhoneNumber_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return PojoProto.internal_static_protobufdemo_proto_Student_PhoneNumber_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                PhoneNumber.class, Builder.class);
            }

            // Construct using com.example.protobufdemo.proto.Student.PhoneNumber.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                number_ = "";

                type_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return PojoProto.internal_static_protobufdemo_proto_Student_PhoneNumber_descriptor;
            }

            public PhoneNumber getDefaultInstanceForType() {
                return PhoneNumber.getDefaultInstance();
            }

            public PhoneNumber build() {
                PhoneNumber result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public PhoneNumber buildPartial() {
                PhoneNumber result = new PhoneNumber(this);
                result.number_ = number_;
                result.type_ = type_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof PhoneNumber) {
                    return mergeFrom((PhoneNumber) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(PhoneNumber other) {
                if (other == PhoneNumber.getDefaultInstance()) return this;
                if (!other.getNumber().isEmpty()) {
                    number_ = other.number_;
                    onChanged();
                }
                if (other.type_ != 0) {
                    setTypeValue(other.getTypeValue());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                PhoneNumber parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (PhoneNumber) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object number_ = "";

            /**
             * <code>optional string number = 1;</code>
             */
            public String getNumber() {
                Object ref = number_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    number_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string number = 1;</code>
             */
            public com.google.protobuf.ByteString
            getNumberBytes() {
                Object ref = number_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    number_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string number = 1;</code>
             */
            public Builder setNumber(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                number_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string number = 1;</code>
             */
            public Builder clearNumber() {

                number_ = getDefaultInstance().getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional string number = 1;</code>
             */
            public Builder setNumberBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                number_ = value;
                onChanged();
                return this;
            }

            private int type_ = 0;

            /**
             * <code>optional .protobufdemo.proto.Student.PhoneType type = 2;</code>
             */
            public int getTypeValue() {
                return type_;
            }

            /**
             * <code>optional .protobufdemo.proto.Student.PhoneType type = 2;</code>
             */
            public Builder setTypeValue(int value) {
                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .protobufdemo.proto.Student.PhoneType type = 2;</code>
             */
            public PhoneType getType() {
                PhoneType result = PhoneType.valueOf(type_);
                return result == null ? PhoneType.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .protobufdemo.proto.Student.PhoneType type = 2;</code>
             */
            public Builder setType(PhoneType value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                type_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .protobufdemo.proto.Student.PhoneType type = 2;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:protobufdemo.proto.Student.PhoneNumber)
        }

        // @@protoc_insertion_point(class_scope:protobufdemo.proto.Student.PhoneNumber)
        private static final PhoneNumber DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new PhoneNumber();
        }

        public static PhoneNumber getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<PhoneNumber>
                PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
            public PhoneNumber parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new PhoneNumber(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<PhoneNumber> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
            return PARSER;
        }

        public PhoneNumber getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;

    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
        return id_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile Object firstName_;

    /**
     * <code>optional string first_name = 2;</code>
     */
    public String getFirstName() {
        Object ref = firstName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            firstName_ = s;
            return s;
        }
    }

    /**
     * <code>optional string first_name = 2;</code>
     */
    public com.google.protobuf.ByteString
    getFirstNameBytes() {
        Object ref = firstName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            firstName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile Object lastName_;

    /**
     * <code>optional string last_name = 3;</code>
     */
    public String getLastName() {
        Object ref = lastName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            lastName_ = s;
            return s;
        }
    }

    /**
     * <code>optional string last_name = 3;</code>
     */
    public com.google.protobuf.ByteString
    getLastNameBytes() {
        Object ref = lastName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            lastName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile Object email_;

    /**
     * <code>optional string email = 4;</code>
     */
    public String getEmail() {
        Object ref = email_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            email_ = s;
            return s;
        }
    }

    /**
     * <code>optional string email = 4;</code>
     */
    public com.google.protobuf.ByteString
    getEmailBytes() {
        Object ref = email_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            email_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PHONE_FIELD_NUMBER = 5;
    private java.util.List<PhoneNumber> phone_;

    /**
     * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
     */
    public java.util.List<PhoneNumber> getPhoneList() {
        return phone_;
    }

    /**
     * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
     */
    public java.util.List<? extends PhoneNumberOrBuilder>
    getPhoneOrBuilderList() {
        return phone_;
    }

    /**
     * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
     */
    public int getPhoneCount() {
        return phone_.size();
    }

    /**
     * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
     */
    public PhoneNumber getPhone(int index) {
        return phone_.get(index);
    }

    /**
     * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
     */
    public PhoneNumberOrBuilder getPhoneOrBuilder(
            int index) {
        return phone_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (id_ != 0) {
            output.writeInt32(1, id_);
        }
        if (!getFirstNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
        }
        if (!getLastNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
        }
        if (!getEmailBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
        }
        for (int i = 0; i < phone_.size(); i++) {
            output.writeMessage(5, phone_.get(i));
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, id_);
        }
        if (!getFirstNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
        }
        if (!getLastNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
        }
        if (!getEmailBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
        }
        for (int i = 0; i < phone_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(5, phone_.get(i));
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Student)) {
            return super.equals(obj);
        }
        Student other = (Student) obj;

        boolean result = true;
        result = result && (getId()
                == other.getId());
        result = result && getFirstName()
                .equals(other.getFirstName());
        result = result && getLastName()
                .equals(other.getLastName());
        result = result && getEmail()
                .equals(other.getEmail());
        result = result && getPhoneList()
                .equals(other.getPhoneList());
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstName().hashCode();
        hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastName().hashCode();
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
        if (getPhoneCount() > 0) {
            hash = (37 * hash) + PHONE_FIELD_NUMBER;
            hash = (53 * hash) + getPhoneList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Student parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Student parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Student parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Student parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Student parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Student parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Student parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Student parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Student parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Student parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Student prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code protobufdemo.proto.Student}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:protobufdemo.proto.Student)
            com.example.protobufdemo.proto.StudentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return PojoProto.internal_static_protobufdemo_proto_Student_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return PojoProto.internal_static_protobufdemo_proto_Student_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Student.class, Builder.class);
        }

        // Construct using com.example.protobufdemo.proto.Student.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getPhoneFieldBuilder();
            }
        }

        public Builder clear() {
            super.clear();
            id_ = 0;

            firstName_ = "";

            lastName_ = "";

            email_ = "";

            if (phoneBuilder_ == null) {
                phone_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000010);
            } else {
                phoneBuilder_.clear();
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return PojoProto.internal_static_protobufdemo_proto_Student_descriptor;
        }

        public Student getDefaultInstanceForType() {
            return Student.getDefaultInstance();
        }

        public Student build() {
            Student result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public Student buildPartial() {
            Student result = new Student(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.id_ = id_;
            result.firstName_ = firstName_;
            result.lastName_ = lastName_;
            result.email_ = email_;
            if (phoneBuilder_ == null) {
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    phone_ = java.util.Collections.unmodifiableList(phone_);
                    bitField0_ = (bitField0_ & ~0x00000010);
                }
                result.phone_ = phone_;
            } else {
                result.phone_ = phoneBuilder_.build();
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Student) {
                return mergeFrom((Student) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Student other) {
            if (other == Student.getDefaultInstance()) return this;
            if (other.getId() != 0) {
                setId(other.getId());
            }
            if (!other.getFirstName().isEmpty()) {
                firstName_ = other.firstName_;
                onChanged();
            }
            if (!other.getLastName().isEmpty()) {
                lastName_ = other.lastName_;
                onChanged();
            }
            if (!other.getEmail().isEmpty()) {
                email_ = other.email_;
                onChanged();
            }
            if (phoneBuilder_ == null) {
                if (!other.phone_.isEmpty()) {
                    if (phone_.isEmpty()) {
                        phone_ = other.phone_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                    } else {
                        ensurePhoneIsMutable();
                        phone_.addAll(other.phone_);
                    }
                    onChanged();
                }
            } else {
                if (!other.phone_.isEmpty()) {
                    if (phoneBuilder_.isEmpty()) {
                        phoneBuilder_.dispose();
                        phoneBuilder_ = null;
                        phone_ = other.phone_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                        phoneBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getPhoneFieldBuilder() : null;
                    } else {
                        phoneBuilder_.addAllMessages(other.phone_);
                    }
                }
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Student parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Student) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private int id_;

        /**
         * <code>optional int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        /**
         * <code>optional int32 id = 1;</code>
         */
        public Builder setId(int value) {

            id_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional int32 id = 1;</code>
         */
        public Builder clearId() {

            id_ = 0;
            onChanged();
            return this;
        }

        private Object firstName_ = "";

        /**
         * <code>optional string first_name = 2;</code>
         */
        public String getFirstName() {
            Object ref = firstName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                firstName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>optional string first_name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getFirstNameBytes() {
            Object ref = firstName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                firstName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string first_name = 2;</code>
         */
        public Builder setFirstName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            firstName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional string first_name = 2;</code>
         */
        public Builder clearFirstName() {

            firstName_ = getDefaultInstance().getFirstName();
            onChanged();
            return this;
        }

        /**
         * <code>optional string first_name = 2;</code>
         */
        public Builder setFirstNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            firstName_ = value;
            onChanged();
            return this;
        }

        private Object lastName_ = "";

        /**
         * <code>optional string last_name = 3;</code>
         */
        public String getLastName() {
            Object ref = lastName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                lastName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>optional string last_name = 3;</code>
         */
        public com.google.protobuf.ByteString
        getLastNameBytes() {
            Object ref = lastName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                lastName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string last_name = 3;</code>
         */
        public Builder setLastName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            lastName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional string last_name = 3;</code>
         */
        public Builder clearLastName() {

            lastName_ = getDefaultInstance().getLastName();
            onChanged();
            return this;
        }

        /**
         * <code>optional string last_name = 3;</code>
         */
        public Builder setLastNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            lastName_ = value;
            onChanged();
            return this;
        }

        private Object email_ = "";

        /**
         * <code>optional string email = 4;</code>
         */
        public String getEmail() {
            Object ref = email_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                email_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>optional string email = 4;</code>
         */
        public com.google.protobuf.ByteString
        getEmailBytes() {
            Object ref = email_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                email_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string email = 4;</code>
         */
        public Builder setEmail(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            email_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional string email = 4;</code>
         */
        public Builder clearEmail() {

            email_ = getDefaultInstance().getEmail();
            onChanged();
            return this;
        }

        /**
         * <code>optional string email = 4;</code>
         */
        public Builder setEmailBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            email_ = value;
            onChanged();
            return this;
        }

        private java.util.List<PhoneNumber> phone_ =
                java.util.Collections.emptyList();

        private void ensurePhoneIsMutable() {
            if (!((bitField0_ & 0x00000010) == 0x00000010)) {
                phone_ = new java.util.ArrayList<PhoneNumber>(phone_);
                bitField0_ |= 0x00000010;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder> phoneBuilder_;

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public java.util.List<PhoneNumber> getPhoneList() {
            if (phoneBuilder_ == null) {
                return java.util.Collections.unmodifiableList(phone_);
            } else {
                return phoneBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public int getPhoneCount() {
            if (phoneBuilder_ == null) {
                return phone_.size();
            } else {
                return phoneBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public PhoneNumber getPhone(int index) {
            if (phoneBuilder_ == null) {
                return phone_.get(index);
            } else {
                return phoneBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public Builder setPhone(
                int index, PhoneNumber value) {
            if (phoneBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePhoneIsMutable();
                phone_.set(index, value);
                onChanged();
            } else {
                phoneBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public Builder setPhone(
                int index, PhoneNumber.Builder builderForValue) {
            if (phoneBuilder_ == null) {
                ensurePhoneIsMutable();
                phone_.set(index, builderForValue.build());
                onChanged();
            } else {
                phoneBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public Builder addPhone(PhoneNumber value) {
            if (phoneBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePhoneIsMutable();
                phone_.add(value);
                onChanged();
            } else {
                phoneBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public Builder addPhone(
                int index, PhoneNumber value) {
            if (phoneBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePhoneIsMutable();
                phone_.add(index, value);
                onChanged();
            } else {
                phoneBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public Builder addPhone(
                PhoneNumber.Builder builderForValue) {
            if (phoneBuilder_ == null) {
                ensurePhoneIsMutable();
                phone_.add(builderForValue.build());
                onChanged();
            } else {
                phoneBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public Builder addPhone(
                int index, PhoneNumber.Builder builderForValue) {
            if (phoneBuilder_ == null) {
                ensurePhoneIsMutable();
                phone_.add(index, builderForValue.build());
                onChanged();
            } else {
                phoneBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public Builder addAllPhone(
                Iterable<? extends PhoneNumber> values) {
            if (phoneBuilder_ == null) {
                ensurePhoneIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, phone_);
                onChanged();
            } else {
                phoneBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public Builder clearPhone() {
            if (phoneBuilder_ == null) {
                phone_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
            } else {
                phoneBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public Builder removePhone(int index) {
            if (phoneBuilder_ == null) {
                ensurePhoneIsMutable();
                phone_.remove(index);
                onChanged();
            } else {
                phoneBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public PhoneNumber.Builder getPhoneBuilder(
                int index) {
            return getPhoneFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public PhoneNumberOrBuilder getPhoneOrBuilder(
                int index) {
            if (phoneBuilder_ == null) {
                return phone_.get(index);
            } else {
                return phoneBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public java.util.List<? extends PhoneNumberOrBuilder>
        getPhoneOrBuilderList() {
            if (phoneBuilder_ != null) {
                return phoneBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(phone_);
            }
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public PhoneNumber.Builder addPhoneBuilder() {
            return getPhoneFieldBuilder().addBuilder(
                    PhoneNumber.getDefaultInstance());
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public PhoneNumber.Builder addPhoneBuilder(
                int index) {
            return getPhoneFieldBuilder().addBuilder(
                    index, PhoneNumber.getDefaultInstance());
        }

        /**
         * <code>repeated .protobufdemo.proto.Student.PhoneNumber phone = 5;</code>
         */
        public java.util.List<PhoneNumber.Builder>
        getPhoneBuilderList() {
            return getPhoneFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder>
        getPhoneFieldBuilder() {
            if (phoneBuilder_ == null) {
                phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder>(
                        phone_,
                        ((bitField0_ & 0x00000010) == 0x00000010),
                        getParentForChildren(),
                        isClean());
                phone_ = null;
            }
            return phoneBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:protobufdemo.proto.Student)
    }

    // @@protoc_insertion_point(class_scope:protobufdemo.proto.Student)
    private static final Student DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new Student();
    }

    public static Student getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
            PARSER = new com.google.protobuf.AbstractParser<Student>() {
        public Student parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Student(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Student> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Student> getParserForType() {
        return PARSER;
    }

    public Student getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

